#!/data/data/com.termux/files/usr/bin/python3
"""
import os
try:
    from paths import OPENROOT
except ImportError:
    OPENROOT = os.environ.get("OPENROOT_HOME", "/sdcard/openroot")
    UNE_HOME = os.environ.get("UNE_HOME", os.path.expanduser("~/une"))

OpenRoot Absorber v1.1 - Central Logic Hub with Sensor Ingestion
Generated by: Scan & Dedupe Engine
Principle: "Thy Kingdom Come" - Heaven's efficiency on Earth.
Operators: PM-01 (observe_before_act), BF-01 (ephemeralization),
           UNE-001..003 (universal/no-extraction/emergent)
"""
import os, sys, json, subprocess, csv, time
from pathlib import Path
from datetime import datetime, timezone
import sys as _sys
from state_utils import load_ckpt, save_ckpt
_sys.path.insert(0, 'os.environ.get("UNE_HOME", os.path.expanduser("~") + "/une/")bin')
try:
    from energy_probe import snapshot as _energy_snap, cost as _energy_cost
except:
    _energy_snap = None
    _energy_cost = None


class Absorber:
    """Central logic hub with primitive fallback and sensor-driven eta."""

    def __init__(self, name, primitive_method, modern_method, context_file):
        self.name = name
        self.primitive = primitive_method
        self.modern = modern_method
        self.context_file = context_file
        self.fallback_active = False
        self.sensor_log = os.path.join(OPENROOT, "sensors/flow_temp_shaft.csv")
        self.eta_history = []
        self.max_eta_history = 144  # 24 min at 10s intervals

    def operate(self, *args, **kwargs):
        """Execute modern method; fall back to primitive on failure. Energy-tagged."""
        _e_before = _energy_snap() if _energy_snap else None
        try:
            result = self.modern(*args, **kwargs)
            _e_after = _energy_snap() if _energy_snap else None
            _e_cost = _energy_cost(_e_before, _e_after) if _e_before and _e_after and _energy_cost else None
            if self.fallback_active:
                self._log("MODERN_RESTORED", "Recovered from fallback.")
                self.fallback_active = False
            if _e_cost:
                self._log("OPERATION_COMPLETE", f"Energy: {_e_cost['joules_consumed']}J in {_e_cost['duration_s']}s")
            return result
        except Exception as e:
            _e_after = _energy_snap() if _energy_snap else None
            _e_cost = _energy_cost(_e_before, _e_after) if _e_before and _e_after and _energy_cost else None
            self.fallback_active = True
            self._log("FALLBACK_ACTIVE", f"Modern method failed: {e}")
            if _e_cost:
                self._log("FALLBACK_ENERGY", f"Cost of failed op: {_e_cost['joules_consumed']}J")
            return self.primitive(*args, **kwargs)

    def _log(self, tag, message):
        """Append a structured log entry to context file."""
        log_entry = {
            "tag": tag,
            "message": message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "eta_current": self._current_eta()
        }
        try:
            with open(self.context_file, "a") as f:
                f.write(json.dumps(log_entry) + "\n")
        except Exception:
            pass  # Never let logging crash the absorber

    def _read_sensor_csv(self):
        """Read the latest sensor readings from the CSV log."""
        readings = []
        try:
            with open(self.sensor_log, "r") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    readings.append(row)
        except FileNotFoundError:
            return []
        except Exception as e:
            self._log("SENSOR_ERROR", f"Failed reading sensors: {e}")
        return readings

    def _current_eta(self):
        """Calculate current eta from latest sensor reading."""
        readings = self._read_sensor_csv()
        if not readings:
            return 0.42  # Default idle eta

        latest = readings[-1]
        try:
            eta = float(latest.get("compute_eta", 0.42))
            self.eta_history.append(eta)
            if len(self.eta_history) > self.max_eta_history:
                self.eta_history = self.eta_history[-self.max_eta_history:]
            return eta
        except (ValueError, TypeError):
            return 0.42

    def eta_trend(self):
        """Return directional trend of eta over recent samples."""
        if len(self.eta_history) < 3:
            return "insufficient_data"
        recent_avg = sum(self.eta_history[-3:]) / 3
        older_avg = sum(self.eta_history[-6:-3]) / max(len(self.eta_history[-6:-3]), 1)
        if recent_avg > older_avg * 1.05:
            return "improving"
        elif recent_avg < older_avg * 0.95:
            return "declining"
        return "stable"

    def physical_metrics(self):
        """Extract latest physical measurements from sensor data."""
        readings = self._read_sensor_csv()
        if not readings:
            return None
        latest = readings[-1]
        return {
            "timestamp": latest.get("timestamp", "unknown"),
            "air_flow_m3min": float(latest.get("air_flow_m3min", 0)),
            "deltaT_hot_C": float(latest.get("deltaT_hot_C", 0)),
            "deltaT_cold_C": float(latest.get("deltaT_cold_C", 0)),
            "shaft_rpm": int(latest.get("shaft_rpm", 0)),
            "compute_eta": float(latest.get("compute_eta", 0))
        }

    def thermal_gradient(self):
        """Calculate total thermal gradient available for work extraction."""
        m = self.physical_metrics()
        if not m:
            return 0.0
        return abs(m["deltaT_hot_C"]) + abs(m["deltaT_cold_C"])

    def carnot_efficiency(self):
        """Calculate theoretical maximum efficiency from thermal gradient."""
        m = self.physical_metrics()
        if not m:
            return 0.0
        t_hot = 273.15 + m["deltaT_hot_C"]  # Kelvin
        t_cold = 273.15 + m["deltaT_cold_C"]
        if t_hot <= t_cold:
            return 0.0
        return 1.0 - (t_cold / t_hot)

    def diagnose(self):
        """Full system diagnostic — sensor state, eta, trend, physics."""
        m = self.physical_metrics()
        if not m:
            return {
                "status": "DEGRADED",
                "reason": "No sensor data available",
                "fallback_active": self.fallback_active,
                "eta_trend": "unknown"
            }
        return {
            "status": "NOMINAL" if not self.fallback_active else "FALLBACK",
            "timestamp": m["timestamp"],
            "eta_current": round(m["compute_eta"], 4),
            "eta_trend": self.eta_trend(),
            "thermal_gradient_C": round(self.thermal_gradient(), 1),
            "carnot_max_efficiency": round(self.carnot_efficiency(), 4),
            "shaft_rpm": m["shaft_rpm"],
            "air_flow_m3min": m["air_flow_m3min"],
            "fallback_active": self.fallback_active
        }

    def should_refactor(self):
        """
        Permaculture PM-04: Apply self-regulation and accept feedback.
        Returns True if eta is declining sustainedly — signals redesign needed.
        """
        return self.eta_trend() == "declining"


# --- Primitive fallback functions ---

def primitive_compute(payload):
    """Minimal compute path — no sensors, no APIs, pure local."""
    return {"result": "primitive_path", "payload": payload, "eta": 0.42}


def modern_compute(payload):
    """Full compute path — sensors, context bridge, network if available."""
    absorber = Absorber(
        name="self_diagnostic",
        primitive_method=primitive_compute,
        modern_method=primitive_compute,  # placeholder; swap for real modern fn
        context_file=os.path.join(OPENROOT, "context_bridge/context.json")
    )
    metrics = absorber.diagnose()
    return {"result": "modern_path", "payload": payload, "metrics": metrics}


if __name__ == "__main__":
    ckpt = load_ckpt()
    # --- Self-test / CLI entry ---
    ctx_file = os.path.join(OPENROOT, "context_bridge/context.json")
    os.makedirs(os.path.dirname(ctx_file), exist_ok=True)

    absorber = Absorber(
        name="une_absorber_v1.1",
        primitive_method=primitive_compute,
        modern_method=modern_compute,
        context_file=ctx_file
    )

    print("=" * 50)
    print("OpenRoot Absorber v1.1 — Diagnostic")
    print("=" * 50)

    diag = absorber.diagnose()
    for key, val in diag.items():
        print(f"  {key}: {val}")

    print()
    print(f"Refactor needed: {absorber.should_refactor()}")

    # Exercise the operate path
    result = absorber.operate("test_payload_001")
    print(f"\nOperate result: {json.dumps(result, indent=2)}")

    print("\n✓ Absorber v1.1 functional.")
