#!/data/data/com.termux/files/usr/bin/python3
"""
ANTIFRAGILE GUARDIAN v4.1 (Hardened)
====================================
Autonomous Architect with Deduplication.
Skips notes already processed to prevent infinite loops.
"""
import os, sys, json, re, subprocess
from datetime import datetime

# Paths
CB_PATH = "/sdcard/openroot/context_bridge/immortal_context_merged.json"
NOTES_FILE = "/sdcard/openroot/notes.txt"
PATCH_DIR = "/sdcard/openroot/patches"
GUARDIAN_LOG = "/sdcard/openroot/guardian_log.jsonl"

os.makedirs(PATCH_DIR, exist_ok=True)

def load_json(path, default=None):
    if os.path.exists(path):
        try:
            with open(path) as f:
                return json.load(f)
        except:
            pass
    return default or {"entries": []}

def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)

def log_event(event_type, details, action_taken=None, patch_code=None):
    entry = {
        "type": event_type,
        "timestamp": datetime.now().isoformat(),
        "details": details,
        "action_taken": action_taken,
        "patch_code": patch_code,
        "efficiency_level": 4 if patch_code else 1
    }
    
    cb = load_json(CB_PATH, {"sources": [], "entries": []})
    if "entries" not in cb: cb["entries"] = []
    cb["entries"].append(entry)
    save_json(CB_PATH, cb)
    
    with open(GUARDIAN_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")
    
    print(f"🛡️  [{event_type}] {details}")
    if patch_code:
        print(f"   💾 Generated Patch: {len(patch_code)} bytes")

def generate_keyerror_fix(error_context):
    fix_snippet = f"""
# Autogenerated Fix for KeyError detected by Guardian v4.1
# Context: {error_context}

def safe_get(dictionary, key, default=None):
    '''Antifragile accessor: prevents KeyError by returning default.'''
    try:
        return dictionary[key]
    except KeyError:
        print(f"Guardian: Missing key {{key}}. Returning default.")
        return default
"""
    return fix_snippet

def get_processed_notes():
    """Load all note texts that have already been processed."""
    processed = set()
    if os.path.exists(GUARDIAN_LOG):
        with open(GUARDIAN_LOG) as f:
            for line in f:
                try:
                    e = json.loads(line)
                    if e.get("type") == "antifragile_heal":
                        # Extract the note text from details
                        details = e.get("details", "")
                        if "Generated patch for KeyError in " in details:
                            note_text = details.replace("Generated patch for KeyError in ", "").strip()
                            processed.add(note_text)
                except:
                    pass
    return processed

def scan_and_heal():
    if not os.path.exists(NOTES_FILE):
        return

    with open(NOTES_FILE) as f:
        lines = f.readlines()

    processed_notes = get_processed_notes()
    healed_count = 0
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"): continue
        
        # Skip if already processed
        if line in processed_notes:
            continue

        if "keyerror" in line.lower() or "missing key" in line.lower():
            print(f"⚠️  Detected NEW KeyError stress: {line[:60]}...")
            
            patch_code = generate_keyerror_fix(line)
            patch_filename = os.path.join(PATCH_DIR, f"fix_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py")
            with open(patch_filename, "w") as f:
                f.write(patch_code)
            
            log_event(
                "antifragile_heal",
                f"Generated patch for KeyError in {line[:40]}...",
                action_taken=f"Saved patch to {patch_filename}",
                patch_code=patch_code
            )
            healed_count += 1

    if healed_count == 0:
        print("✅ No new stress requiring code generation.")
    else:
        print(f"🎉 Healing Complete. {healed_count} new patches generated.")

def main():
    print("🛡️  Guardian v4.1 (Hardened) Starting...")
    scan_and_heal()
    print("🏁 Cycle Complete.")

if __name__ == "__main__":
    main()
