#!/usr/bin/env python3
"""
REPO ANALYZER — Scans, upgrades, and pushes changes to all repos in the hub.
"""
import os, sys, json, subprocess, ast
from datetime import datetime

HUB_PATH = "/data/data/com.termux/files/home/une/meta_hub"
LOG_FILE = "/sdcard/openroot/meta_orchestrator.log"

def log(msg):
    print(msg)
    with open(LOG_FILE, "a") as f:
        f.write(msg + "\n")

def analyze_repo(repo_path, repo_name):
    report = {
        "name": repo_name, "path": repo_path,
        "analyzed_at": datetime.now().isoformat(),
        "files_total": 0, "python_files": 0,
        "syntax_errors": [], "tests_pass": None,
        "missing_standard_files": [], "upgrades_applied": [],
        "status": "analyzed"
    }

    if not os.path.exists(repo_path):
        report["status"] = "missing"
        return report

    # Scan files
    all_files = []
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__')]
        for f in files:
            fp = os.path.join(root, f)
            rel = os.path.relpath(fp, repo_path)
            all_files.append(rel)
            if f.endswith('.py'):
                report["python_files"] += 1
                try:
                    with open(fp, 'r', errors='replace') as fh:
                        ast.parse(fh.read())
                except SyntaxError as e:
                    report["syntax_errors"].append({"file": rel, "error": str(e)})

    report["files_total"] = len(all_files)

    # Check standard files
    checks = {
        "has_readme": "README.md", "has_gitignore": ".gitignore",
        "has_license": "LICENSE", "has_requirements": "requirements.txt"
    }
    for key, fname in checks.items():
        report[key] = os.path.exists(os.path.join(repo_path, fname))
        if not report[key]:
            report["missing_standard_files"].append(fname)

    # Auto-generate missing files
    if not report["has_readme"]:
        readme_content = f"# {repo_name}\n\nAuto-generated by Meta-Orchestrator.\n"
        with open(os.path.join(repo_path, "README.md"), "w") as f:
            f.write(readme_content)
        report["upgrades_applied"].append("generated README.md")

    if not report["has_gitignore"]:
        with open(os.path.join(repo_path, ".gitignore"), "w") as f:
            f.write("__pycache__/\n*.pyc\n.env\nnode_modules/\n")
        report["upgrades_applied"].append("generated .gitignore")

    if not report["has_license"]:
        with open(os.path.join(repo_path, "LICENSE"), "w") as f:
            f.write("AGPL-3.0 License\nCopyright (c) Jesse Ray\n")
        report["upgrades_applied"].append("generated LICENSE")

    # Generate contribution file
    contrib_dir = os.path.join(repo_path, "contributions")
    os.makedirs(contrib_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    contrib_file = os.path.join(contrib_dir, f"meta_upgrade_{ts}.py")
    
    with open(contrib_file, "w") as f:
        f.write(f'#!/usr/bin/env python3\nprint("Upgrade applied to {repo_name}")\n')
    report["upgrades_applied"].append(f"created contribution file")

    # Commit and Push
    subprocess.run(["git", "add", "-A"], cwd=repo_path, capture_output=True)
    msg = f"feat: Meta-Orchestrator upgrade ({len(report['upgrades_applied'])} changes)"
    subprocess.run(["git", "commit", "--no-verify", "-m", msg], cwd=repo_path, capture_output=True)
    
    r = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=repo_path, capture_output=True, text=True)
    report["commit_hash"] = r.stdout.strip()

    branch_r = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=repo_path, capture_output=True, text=True)
    branch = branch_r.stdout.strip()
    
    push_r = subprocess.run(["git", "push", "origin", branch], cwd=repo_path, capture_output=True, text=True)
    if push_r.returncode == 0:
        report["status"] = "pushed"
    else:
        report["status"] = "committed_local"

    return report

def main():
    if not os.path.exists(HUB_PATH):
        print(f"HUB not found: {HUB_PATH}")
        return

    repos = []
    for item in os.listdir(HUB_PATH):
        item_path = os.path.join(HUB_PATH, item)
        if os.path.isdir(item_path) and os.path.exists(os.path.join(item_path, ".git")):
            repos.append((item, item_path))

    if not repos:
        print("No repos found.")
        return

    all_reports = []
    for name, path in sorted(repos):
        try:
            rep = analyze_repo(path, name)
            all_reports.append(rep)
        except Exception as e:
            all_reports.append({"name": name, "status": "error", "error": str(e)})

    # Save reports
    with open(os.path.join(HUB_PATH, "repo_reports.json"), "w") as f:
        json.dump(all_reports, f, indent=2)

    # Generate Manual
    manual = "# 🧬 OpenRoot Ecosystem Manual\n\n"
    manual += f"## Repositories ({len(all_reports)})\n\n"
    for r in all_reports:
        manual += f"### {r['name']}\n- Status: {r['status']}\n- Files: {r.get('files_total', 0)}\n- Upgrades: {', '.join(r.get('upgrades_applied', ['None']))}\n\n"
    
    with open(os.path.join(HUB_PATH, "UNIFIED_MANUAL.md"), "w") as f:
        f.write(manual)

    # Generate Dashboard HTML
    total_files = sum(r.get('files_total', 0) for r in all_reports)
    total_upgrades = sum(len(r.get('upgrades_applied', [])) for r in all_reports)
    
    html = f"""<!DOCTYPE html>
<html><head><title>OpenRoot Dashboard</title>
<style>body{{font-family:monospace;background:#0d0d0d;color:#e0e0e0;padding:20px;}}
h1{{color:#6d4aff;border-bottom:2px solid #6d4aff;}}
.card{{background:#1a1a2e;border:1px solid #333;padding:15px;margin:10px 0;border-radius:8px;}}
.stat{{display:inline-block;margin-right:15px;color:#6d4aff;}}</style></head>
<body>
<h1>🧬 OpenRoot Ecosystem Dashboard</h1>
<div class="stat">Repos: {len(all_reports)}</div>
<div class="stat">Files: {total_files}</div>
<div class="stat">Upgrades: {total_upgrades}</div>
<hr>
"""
    for r in all_reports:
        status_color = "#00ff88" if r['status'] == 'pushed' else '#ffaa00'
        html += f'<div class="card"><h2 style="color:{status_color}">{r["name"]}</h2>'
        html += f'<p>Status: {r["status"]} | Files: {r.get("files_total",0)} | Upgrades: {", ".join(r.get("upgrades_applied", ["None"]))}</p>'
        html += f'<a href="https://github.com/jesseray718/{r["name"]}" target="_blank">View on GitHub →</a></div>\n'
    
    html += "</body></html>"
    with open(os.path.join(HUB_PATH, "index.html"), "w") as f:
        f.write(html)

    print(f"✅ Done. Reports saved. Manual and Dashboard generated.")

if __name__ == "__main__":
    main()
