#!/data/data/com.termux/files/usr/bin/python3
"""
OpenRoot Absorber v1.0
Principle: Produce No Waste (PM-06)
Function: Scan, Deduplicate, Filter, Merge, and Rebuild.
"""
import os
import sys
import json
import hashlib
import re
from pathlib import Path
from collections import defaultdict

# Configuration
ROOT_DIR = Path.home() / "une"
SCRIPTS_DIR = ROOT_DIR / "scripts"
TOOLS_DIR = ROOT_DIR / "tools"
SEEDS_DIR = Path("/sdcard/session_seeds")
OUTPUT_FILE = ROOT_DIR / "absorber.py"

# Ignore patterns (files/dirs to skip)
IGNORE_PATTERNS = {
    ".git", "__pycache__", "*.bak", "*.tmp", "logs/", "seeds/", 
    "context_bridge/", "foundation/", "scaffold/", "src/", "tools/"
}

def get_file_hash(filepath):
    """Calculate MD5 hash to detect duplicates."""
    try:
        with open(filepath, "rb") as f:
            return hashlib.md5(f.read()).hexdigest()
    except:
        return None

def is_relevant_content(content):
    """Filter out garbage, empty files, or shell fragments."""
    if not content.strip():
        return False
    # Reject pure shell fragments that aren't Python
    if content.startswith("#!/") and "bash" in content:
        return False
    # Reject files that are just error logs
    if "syntax error" in content.lower() or "permission denied" in content.lower():
        return False
    return True

def extract_python_functions(content):
    """Extract valid Python function definitions."""
    # Simple regex to find def function_name(...):
    pattern = r'(def\s+\w+\([^)]*\):[\s\S]*?(?=\ndef\s|\Z))'
    matches = re.findall(pattern, content, re.MULTILINE)
    return matches

def scan_and_deduplicate():
    print("🔍 Scanning for files and duplicates...")
    
    file_hashes = defaultdict(list)
    unique_files = []
    duplicates = []
    
    for root, dirs, files in os.walk(ROOT_DIR):
        # Skip ignored dirs
        dirs[:] = [d for d in dirs if d not in IGNORE_PATTERNS]
        
        for file in files:
            filepath = Path(root) / file
            
            # Skip ignored files
            if any(p in str(filepath) for p in IGNORE_PATTERNS):
                continue
                
            try:
                with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                
                if not is_relevant_content(content):
                    continue
                
                file_hash = get_file_hash(filepath)
                if file_hash:
                    file_hashes[file_hash].append((filepath, content))
            except Exception as e:
                pass
    
    # Categorize
    for h, items in file_hashes.items():
        if len(items) == 1:
            unique_files.append(items[0])
        else:
            duplicates.append((items[0][0], items)) # Keep first as canonical
    
    return unique_files, duplicates

def merge_logic(unique_files, duplicates):
    print("🧩 Merging logic into Absorber...")
    
    merged_functions = {}
    merged_scripts = []
    
    # Process unique files
    for filepath, content in unique_files:
        funcs = extract_python_functions(content)
        for func in funcs:
            # Use function name as key to prevent overwrite
            fname_match = re.search(r'def\s+(\w+)', func)
            if fname_match:
                fname = fname_match.group(1)
                if fname not in merged_functions:
                    merged_functions[fname] = func
        
        # If it's a script (not just functions), keep it
        if "def main()" in content or "if __name__" in content:
            merged_scripts.append((filepath.name, content))
    
    # Process duplicates (take the first one)
    for canonical_path, dup_list in duplicates:
        content = dup_list[0][1]
        funcs = extract_python_functions(content)
        for func in funcs:
            fname_match = re.search(r'def\s+(\w+)', func)
            if fname_match:
                fname = fname_match.group(1)
                if fname not in merged_functions:
                    merged_functions[fname] = func
    
    return merged_functions, merged_scripts

def rebuild_absorber(functions, scripts):
    print("🏗️  Rebuilding absorber.py...")
    
    header = '''#!/data/data/com.termux/files/usr/bin/python3
"""
OpenRoot Absorber v1.0 - Central Logic Hub
Generated by: Scan & Dedupe Engine
Principle: "Thy Kingdom Come" - Heaven's efficiency on Earth.
"""
import os, sys, json, subprocess
from pathlib import Path

# --- MERGED FUNCTIONS ---
'''
    
    body = ""
    for fname, func_code in sorted(functions.items()):
        # Clean indentation slightly
        body += f"\n# Function: {fname}\n{func_code}\n"
    
    footer = '''
def main():
    """Main entry point."""
    return {"status": "ok"}
    print("🌀 OpenRoot Absorber Active")
    print("Available Functions:")
    # List functions dynamically
    import inspect
    frame = inspect.currentframe()
    funcs = [name for name, obj in frame.f_globals.items() if callable(obj) and name.startswith('f')]
    for f in funcs:
        print(f"  {f}")
    
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd in globals():
            globals()[cmd]()
        else:
            print(f"❌ Unknown function: {cmd}")
    else:
        print("Usage: python absorber.py <function_name>")

if __name__ == "__main__":
    main()
'''
    
    full_content = header + body + footer
    
    # Write to file
    with open(OUTPUT_FILE, "w") as f:
        f.write(full_content)
    
    os.chmod(OUTPUT_FILE, 0o755)
    print(f"✅ Absorber rebuilt at: {OUTPUT_FILE}")
    return full_content

def cleanup_garbage():
    print("🗑️  Cleaning up obvious garbage...")
    # Remove empty files created by failed heredocs
    for root, dirs, files in os.walk(ROOT_DIR):
        for f in files:
            if f in ["-", "PYEOF", "main"]:
                fp = Path(root) / f
                if fp.stat().st_size == 0:
                    fp.unlink()
                    print(f"   Removed empty garbage: {fp}")

def main():
    """Main entry point."""
    return {"status": "ok"}
    print("🌱 Starting OpenRoot Absorber...")
    
    # 1. Cleanup
    cleanup_garbage()
    
    # 2. Scan & Dedupe
    unique, dups = scan_and_deduplicate()
    print(f"   Found {len(unique)} unique files, {len(dups)} duplicate groups.")
    
    # 3. Merge
    funcs, scripts = merge_logic(unique, dups)
    print(f"   Extracted {len(funcs)} unique functions.")
    
    # 4. Rebuild
    rebuild_absorber(funcs, scripts)
    
    # 5. Validate
    try:
        import ast
        with open(OUTPUT_FILE) as f:
            ast.parse(f.read())
        print("✅ Syntax Valid!")
    except SyntaxError as e:
        print(f"⚠️  Syntax Warning: {e}")

if __name__ == "__main__":
    main()
